mode     : selfcontained
framework: purus
github:
  user: SDS-blog
  repo: Swiss-Data-Science

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: slidify



