title: Swiss Data Science
tagline: Blog with examples of our work
logo: assets/img/poirot.jpg 
owner: Christian Ruiz
author:
  email: ruiz.crp@gmail.com
  github: SDS-blog
  firstname: Christian
  lastname: Ruiz

social:
  github: SDS-blog
  twitter: christian_ruiz_

# Choose url: / for local development
url: http://sds-blog.github.io/swiss-data-science/
rawurl: https://raw.github.com/sds-blog/swiss-data-science/gh-pages/
# url: /
URL: http://github.com/sds-blog/swiss-data-science
navigation: 
  - {item: Home, href: index.html}
  - {item: About, href: about.html}
